"""add experience column

Revision ID: f00c375bcd0a
Revises: 68b2c2de25e4
Create Date: 2026-04-08 22:44:10.738858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00c375bcd0a'
down_revision: Union[str, Sequence[str], None] = '68b2c2de25e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('experience', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'experience')
    # ### end Alembic commands ###
